# codemagic.yaml
# Complete documentation at https://docs.codemagic.io/yaml/configuration-reference/

workflows:
  ios-workflow:
    name: iOS Build and Simulator Test
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # Define any environment variables here
        BUNDLE_ID: "com.krew.movers"
    scripts:
      - name: Fetch dependencies
        script: | 
          flutter packages pub get
      - name: Run Unit & Widget Tests
        script: | 
          flutter test
      - name: Build iOS IPA
        script: | 
          # Building unsigned IPA for testing
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - <YOUR_EMAIL@EXAMPLE.COM>
